### ISSUE TITLE
HeatVision moddb

### ISSUE THREAD

**Issue by pockerhead** [vegeta1k95/BillingLibrary#1]
Hello! Can you submit the source code of your modified binaries in the HeatVision mod on GitHub or send me a mail? 
I'm going to re-release your mod and support it in the future

my mail pockerhead@yandex.ru
delete issue after
Best regards

**Comment by pockerhead** [comment]
@vegeta1k95

**Comment by vegeta1k95** [comment]
@pockerhead 
Unfortunately, I was not supporting the mod for quite a long time and will not plan to do so in the future. I've seen people asking for source code. Here is an archive with: 
1) Engine source files, to which I have made changes to 
2) Gamedata files: scripts, shaders, etc 

Changes I've made to source files are commented with 
```
//--DSR-- HeatVision_start
(come code here) 
//--DSR-- HeatVision_end
```

so you can easily identify changes. 

BEWARE, THESE ARE FILES FROM 1.5.1 VERSION!

https://drive.google.com/file/d/16SmQLjEx12jl1xIAFsqpet2Fh2TNfBtc/view?usp=sharing
